blogs/urls.py
from django.urls import path
from .views import blog1_view, blog2_view

app_name="blogs"

urlpatterns = [
    path('blog1/', blog1_view, name='blog1'),
    path('blog2/', blog2_view, name='blog2'),
    # other paths...
]

home/urls.py
# home/urls.py
from django.urls import path
from .views import home, team_view, about, mission, blog

urlpatterns = [
    path('', home, name='home'),
    path('team/', team_view, name='team'),
    path('about/', about, name='about'),
    path('mission/', mission, name='mission'),
    path('blog/', blog, name='blog'),

    
]

blogs/models.py
from django.db import models

# Create your models here.

blogs/views.py
from django.shortcuts import render

def blog1_view(request):
    # Your view logic here
    return render(request, 'blog1.html')

def blog2_view(request):
    # Your view logic here
    return render(request, 'blog2.html')

from django.shortcuts import redirect

home/views.py
# home/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect, HttpResponse

def home(request):
    return render(request, 'home.html')

def team_view(request):
    return render(request, 'team.html')

def about(request):
    return render(request, 'about.html')

def mission(request):
    return render(request, 'mission.html')

def blog(request):
    return render(request, 'blog.html')

home/templates/blog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<style>
@import url("https://fonts.googleapis.com/css2?family=Roboto&display=swap");
body {

  background-color: #fff;
  color: #10182f;
}


</style>




<div class="container1blog containerblog">

    <a href="{% url 'blogs:blog2' %}">
        <div class="card-blog">
      <div class="card-blog-header">
        <img loading="lazy" src="{% static 'images/blogs/blog1.jpg' %}" alt="rover" />
      </div>
      <div class="card-blog-body">
        <span class="tag tag-teal">Technology</span>
        <h4>
            Unlocking Your College Network: 
        </h4>
        <p>
            Build Connections That Matter
        </p>
        <div class="user">
          <img loading="lazy" src="{% static 'images/team/himanshu.jpg' %}" alt="user" />
          <div class="user-info">
            <h5>Himanshu Shekhar</h5>
            <small>2h ago</small>
          </div>
        </div>
      </div>
    </div>
</a>

    <a href="{% url 'blogs:blog1' %}">
        <div class="card-blog">        
            <div class="card-blog-header">
          <img loading="lazy" src="{% static 'images/blogs/blog2.jpg' %}" alt="ballons" />
        </div>
        <div class="card-blog-body">
          <span class="tag tag-purple">Popular</span>
          <h4>
            Level Up Your College Journey: </h4>
          <p>
            Essential Resources at Your Fingertips           </p>
          <div class="user">
            <img loading="lazy" src="{% static 'images/team/amsanjeev.jpg' %}" alt="user" />
            <div class="user-info">
              <h5>A M Sanjeev</h5>
              <small>Yesterday</small>
            </div>
          </div>
        </div>
      </div>
    </a>


    <a href="#">
      <div class="card-blog">
        <div class="card-blog-header">
          <img loading="lazy" src="{% static 'images/blogs/blog3.jpg' %}" alt="ballons" />
        </div>
        <div class="card-blog-body">
          <span class="tag tag-purple">Popular</span>
          <h4>
            From Freshman to Graduate:           </h4>
          <p>
            Navigating College with Confidence
          </p>
          <div class="user">
            <img loading="lazy" src="{% static 'images/team/amsanjeev.jpg' %}" alt="user" />
            <div class="user-info">
              <h5>A M Sanjeev</h5>
              <small>Yesterday</small>
            </div>
          </div>
        </div>
      </div>
    </a>


    <a href="#">
      <div class="card-blog">
        <div class="card-blog-header">
          <img loading="lazy" src="{% static 'images/blogs/blog4.jpg' %}" alt="ballons" />
        </div>
        <div class="card-blog-body">
          <span class="tag tag-purple">Popular</span>
          <h4>
            Beyond the Classroom:         </h4>
          <p>
            College Connect - Where Collaboration Thrives  
          </p>
          <div class="user">
            <img loading="lazy" src="{% static 'images/team/amsanjeev.jpg' %}" alt="user" />
            <div class="user-info">
              <h5>A M Sanjeev</h5>
              <small>Yesterday</small>
            </div>
          </div>
        </div>
      </div>
    </a>


    <a href="#">
      <div class="card-blog">
        <div class="card-blog-header">
          <img loading="lazy" src="{% static 'images/blogs/blog5.jpg' %}" alt="ballons" />
        </div>
        <div class="card-blog-body">
          <span class="tag tag-purple">Popular</span>
          <h4>
            Crushing College Applications:          </h4>
          <p>
            Get Matched with the Perfect Program 
          </p>
          <div class="user">
            <img loading="lazy" src="{% static 'images/team/amsanjeev.jpg' %}" alt="user" />
            <div class="user-info">
              <h5>A M Sanjeev</h5>
              <small>Yesterday</small>
            </div>
          </div>
        </div>
      </div>
    </a>


    <a href="#">
      <div class="card-blog">
        <div class="card-blog-header">
          <img loading="lazy" src="{% static 'images/blogs/blog6.jpg' %}" alt="ballons" />
        </div>
        <div class="card-blog-body">
          <span class="tag tag-purple">Popular</span>
          <h4>
            From Dorm Room to Dream Job:         </h4>
          <p>
            Your Career Launchpad Starts Here  
          </p>
          <div class="user">
            <img loading="lazy" src="{% static 'images/team/amsanjeev.jpg' %}" alt="user" />
            <div class="user-info">
              <h5>A M Sanjeev</h5>
              <small>Yesterday</small>
            </div>
          </div>
        </div>
      </div>
    </a>


    <a href="#">
      <div class="card-blog">
        <div class="card-blog-header">
          <img loading="lazy" src="{% static 'images/blogs/blog7.jpg' %}" alt="ballons" />
        </div>
        <div class="card-blog-body">
          <span class="tag tag-purple">Popular</span>
          <h4>
            More Than Grades: 
        </h4>
          <p>
            Building a Support System for Academic Success 
          </p>
          <div class="user">
            <img loading="lazy" src="{% static 'images/team/amsanjeev.jpg' %}" alt="user" />
            <div class="user-info">
              <h5>A M Sanjeev</h5>
              <small>Yesterday</small>
            </div>
          </div>
        </div>
      </div>
    </a>



    <a href="#">
      <div class="card-blog">
        <div class="card-blog-header">
          <img loading="lazy" src="{% static 'images/blogs/blog8.jpg' %}" alt="ballons" />
        </div>
        <div class="card-blog-body">
          <span class="tag tag-purple">Popular</span>
          <h4>
            From Coast to Coast (or Across the Globe):          </h4>
          <p>
            Connect with Your College Community 
          </p>
          <div class="user">
            <img loading="lazy" src="{% static 'images/team/amsanjeev.jpg' %}" alt="user" />
            <div class="user-info">
              <h5>A M Sanjeev</h5>
              <small>Yesterday</small>
            </div>
          </div>
        </div>
      </div>
</a>


    <a href="#">
      <div class="card-blog">
      <div class="card-blog-header">
        <img loading="lazy" src="{% static 'images/blogs/blog9.jpg' %}" alt="city" />
      </div>
      <div class="card-blog-body">
        <span class="tag tag-pink">Design</span>
        <h4>
            College Connect:         </h4>
        <p>
            Your Partner in Empowering the Next Generation         </p>
        <div class="user">
            <img loading="lazy" src="{% static 'images/team/akarsh.jpg' %}" alt="user" />
          <div class="user-info">
            <h5>Akarsh Kumar</h5>
            <small>1w ago</small>
          </div>
        </div>
      </div>
    </a>


</div>



{% endblock %}

home/templates/mission.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>


<div class="mission">
  <br><br><br>
  <p class="text-blk team-head-text">
    Our Mission
  </p>

  <section class="mission-section">
    <div class="photo-cluster-upper">
    <div class="photo-cluster">
      <div class="photo-group photo-1">
        <img src="{% static 'images/mission/1.jpg' %}" alt="Photo 1">
        <img src="{% static 'images/mission/2.jpg' %}" alt="Photo 2">
      </div>
      <div class="photo-group photo-2">
        <img src="{% static 'images/mission/3.jpg' %}" alt="Photo 3">
        <img src="{% static 'images/mission/4.jpg' %}" alt="Photo 4">
      </div>
      <div class="photo-group photo-3">
        <img src="{% static 'images/mission/5.jpg' %}" alt="Photo 5">
        <img src="{% static 'images/mission/6.jpg' %}" alt="Photo 6">
      </div>
      <div class="photo-group photo-4">
        <img src="{% static 'images/mission/7.jpg' %}" alt="Photo 7">
        <img src="{% static 'images/mission/8.jpg' %}" alt="Photo 8">
      </div>
      <div class="photo-group photo-5">
        <img src="{% static 'images/mission/9.jpg' %}" alt="Photo 9">
        <img src="{% static 'images/mission/10.jpg' %}" alt="Photo 10">
      </div>
      <div class="photo-group photo-6">
        <img src="{% static 'images/mission/11.jpg' %}" alt="Photo 11">
        <img src="{% static 'images/mission/12.jpg' %}" alt="Photo 12">
      </div>

      <div class="content-wrapper content-wrapper1 ">

    <div class="container1-mission">
      <h1 style="color:black;">Who We Are</h1>
      <div class="underline" style="width:220px;"></div>
      <p>College Connect is a transformative digital platform born out of a collective vision to revolutionize the collegiate experience. Our mission is to redefine the boundaries of academia, fostering not only academic excellence but also connectivity, collaboration, and individual growth among students worldwide.</p>

    
      <h1 style="color:black;">Overview</h1>
      <div class="underline"  style="width:170px;"></div>
      <p>The College Connect project is a pioneering endeavor that aims to transform the landscape of higher education. It is designed to navigate the complexities of student life by providing an integrated digital ecosystem that addresses academic, social, and professional needs.</p>
    
      <h1 style="color:black;">Key Objectives</h1>
      <div class="underline" style="width:270px;"></div>
      <ol>
        <li><strong style="color:#000;">Academic Excellence:</strong> We strive to provide students with a platform that enhances their learning experience beyond conventional methods, offering access to diverse educational resources and collaborative learning tools.</li>
        <li><strong style="color:#000;">Social Connectivity:</strong> College Connect endeavors to create a digital space that encourages meaningful interactions, fosters collaboration, and nurtures a sense of belonging among students.</li>
        <li><strong style="color:#000;">Career Preparedness:</strong> We are committed to equipping students with the skills necessary for a successful transition into the workforce by offering a suite of career development tools, job listings, and connections to industry experts.</li>
      </ol>
    
      <h1 style="color:black;">Transformative Potential</h1>
      <div class="underline" style="width:430px;"></div>
      <p>Through our rigorous literature review, we have uncovered the transformative potential of social networking platforms in higher education. By leveraging these insights, College Connect aims to provide students with more than just a digital platform; it aspires to be a dynamic ecosystem where social networking becomes a powerful tool for academic enrichment.</p>
    </div>
    
    

    <div class="photo-cluster-lower">

      <div class="photo-group photo-7">
        <img src="{% static 'images/mission/13.jpg' %}" alt="Photo 13">
        <img src="{% static 'images/mission/14.jpg' %}" alt="Photo 14">
      </div>
      <div class="photo-group photo-8">
        <img src="{% static 'images/mission/15.jpg' %}" alt="Photo 15">
        <img src="{% static 'images/mission/16.jpg' %}" alt="Photo 16">
      </div>
      <div class="photo-group photo-9">
        <img src="{% static 'images/mission/17.jpg' %}" alt="Photo 17">
        <img src="{% static 'images/mission/18.jpg' %}" alt="Photo 18">
      </div>
      <div class="photo-group photo-10">
        <img src="{% static 'images/mission/19.jpg' %}" alt="Photo 19">
        <img src="{% static 'images/mission/20.jpg' %}" alt="Photo 20">
      </div>
      <div class="photo-group photo-11">
        <img src="{% static 'images/mission/21.jpg' %}" alt="Photo 21">
        <img src="{% static 'images/mission/22.jpg' %}" alt="Photo 22">
      </div>
      {% comment %} <div class="photo-group photo-12">
        <img src="{% static 'images/mission/23.jpg' %}" alt="Photo 23">
        <img src="{% static 'images/mission/24.jpg' %}" alt="Photo 24">
      </div> {% endcomment %}
        </div>
        <div class="content-wrapper content-wrapper2">




            
            <div class="container1-mission">
              <h1 style="color:black;">Our Services</h1>
              <div class="underline" style="width:220px;"></div>
              <p>College Connect offers a range of services aimed at enhancing the collegiate experience:</p>
        
            
              <h1 style="color:black;">Potential Impact</h1>
              <div class="underline" style="width:300px;"></div>
              <p>Through our services, College Connect aims to empower students and revolutionize the way they engage with higher education. By fostering a supportive and inclusive community, we strive to unlock each student's full potential and prepare them for success in both their academic and professional endeavors.</p>
            </div>

        </div>
    </div>
  </section>
</div>
{% endblock %}

home/templates/team.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
<br><br><br>
<p class="text-blk team-head-text">
    Our Team
  </p>
<div class="home" id="home">
    
    <div class="container-block container">

        <div class="responsive-container-block teamcard-container">          


            <div class="responsive-cell-block wk-desk-3 wk-mobile-12 wk-tab-4 wk-ipadp-4 team-card-container">
                <div class="team-card">
                <div class="team-card-inner">
                <div class="team-card-front">
                    <div class="team-img-wrapper">
                    <img class="team-img" src="{% static 'images/team/amsanjeev.jpg' %}" alt="A M Sanjeev">
                    </div>
                    <div class="team-card-content">
                    <p class="text-blk name">A M Sanjeev</p>
                    <p class="text-blk position">Full Stack Developer & UI/UX Designer</p>
                    </div>
                </div>
                <div class="team-card-back">
                    <div class="team-card-content">
                    <p class="text-blk name">About A M Sanjeev</p>
                    <br>
                    <p class="text-blk">A M Sanjeev, final-year CS student with expertise in web dev, HTML, CSS, JavaScript, Angular, Node.js, Ruby on Rails, OOP. Proficient in software testing, leadership, and content writing.</p>
                    </div>
                </div>
                </div>
                </div>
                <div  class="social-buttons-team"> 
                    <div class="contacts">
                    <ul>
                        <li>
                        <a href="https://github.com/AMSANJEEV28" target="_blank"
                            ><i class="fab fa-github"></i
                        ></a>
                        </li>
                        <li>
                        <a
                            href="https://www.linkedin.com/in/a-m-sanjeev-456431207/"
                            target="_blank"
                            ><i class="fab fa-linkedin"></i
                        ></a>
                        </li>
                        <li>
                        <a href="mailto:206320028@gkv.ac.in" target="_blank"
                            ><i class="fab fa-google"></i
                        ></a>
                        </li>
                        <li>
                        <a
                            href="https://www.youtube.com/@amsanjeev28/channels"
                            target="_blank"
                            ><i class="fab fa-youtube"></i
                        ></a>
                        </li>
                        <li>
                        <a
                            href="https://dev-academy.com/contributors/a-m-sanjeev"
                            target="_blank"
                            ><i class="fas fa-pen"></i
                        ></a>
                        </li>
                    </ul>
                    </div>

                </div>

            </div> 
              
            <div class="responsive-cell-block wk-desk-3 wk-mobile-12 wk-tab-4 wk-ipadp-4 team-card-container">
            <div class="team-card">
                <div class="team-card-inner">
                <div class="team-card-front">
                    <div class="team-img-wrapper">
                    <img class="team-img" src="{% static 'images/team/himanshu.jpg' %}" alt="A M Sanjeev">
                    </div>
                    <div class="team-card-content">
                    <p class="text-blk name">Himanshu Shekhar</p>
                    <p class="text-blk position">Front-end Designer and Database Architect</p>
                    </div>
                </div>
                <div class="team-card-back">
                    <div class="team-card-content">
                    <p class="text-blk name">About Himanshu Shekhar</p>
                    <br>
                    <p class="text-blk">Himanshu Shekhar, pursuing a Bachelor of Tech in Computer Science. Aiming to be a Fullstack dev, keen on infrastructure. Strong in JS, Python, Java. Eager to learn.</p>
                    </div>
                </div>
                </div>
            </div>
            <div  class="social-buttons-team"> 
                    <div class="contacts">
                    <ul>
                        <li>
                        <a href="https://github.com/Shekhar1276" target="_blank"
                            ><i class="fab fa-github"></i
                        ></a>
                        </li>
                        <li>
                        <a
                            href="https://www.linkedin.com/in/himanshu-shekhar-430175221/"
                            target="_blank"
                            ><i class="fab fa-linkedin"></i
                        ></a>
                        </li>
                        <li>
                        <a href="hshekhar6008@gmail.com" target="_blank"
                            ><i class="fab fa-google"></i
                        ></a>
                        </li>
                        <li>
                        <a
                            href="https://twitter.com/Shekhar1276"
                            target="_blank"
                            ><i class="fab fa-twitter"></i
                        ></a>
                        </li>
                        {% comment %} <li>
                        <a
                            href=""
                            target="_blank"
                            ><i class="fas fa-pen"></i
                        ></a>
                        </li> {% endcomment %}
                    </ul>
                    </div>

            </div>

            </div>          
              
            <div class="responsive-cell-block wk-desk-3 wk-mobile-12 wk-tab-4 wk-ipadp-4 team-card-container">
                <div class="team-card">
                <div class="team-card-inner">
                    <div class="team-card-front">
                    <div class="team-img-wrapper">
                        <img class="team-img" src="{% static 'images/team/akarsh.jpg' %}" alt="A M Sanjeev">
                    </div>
                    <div class="team-card-content">
                        <p class="text-blk name">Akarsh Kumar Pandey</p>
                        <p class="text-blk position">Front-end Developer</p>
                    </div>
                    </div>
                    <div class="team-card-back">
                    <div class="team-card-content">
                        <p class="text-blk name">About Akarsh Kumar Pandey</p>
                        <br>
                        <p class="text-blk">Akarsh Kumar Pandey is a Full Stack Web Developer, React.js, DS & algorithms. Experienced in software dev, interning at CodeClause & Oasis Infobyte.</p>
                    </div>
                    </div>
                </div>
                </div>
                <div  class="social-buttons-team"> 
                    <div class="contacts">
                        <ul>
                        <li>
                            <a href="https://github.com/AKARSH1593" target="_blank"
                            ><i class="fab fa-github"></i
                            ></a>
                        </li>
                        <li>
                            <a
                            href="https://www.linkedin.com/in/akarsh-kumar-pandey-58499311b/"
                            target="_blank"
                            ><i class="fab fa-linkedin"></i
                            ></a>
                        </li>
                        <li>
                            <a href="akarsh.1593ap@gmail.com" target="_blank"
                            ><i class="fab fa-google"></i
                            ></a>
                        </li>
                        {% comment %} <li>
                            <a
                            href=""
                            target="_blank"
                            ><i class="fab fa-youtube"></i
                            ></a>
                        </li>
                        <li>
                            <a
                            href=""
                            target="_blank"
                            ><i class="fas fa-pen"></i
                            ></a>
                        </li> {% endcomment %}
                        </ul>
                    </div>
    
                </div>
    
            </div>

        </div>
    </div>
</div>

{% endblock %}