home/urls.py
# home/urls.py
from django.urls import path
from .views import home, team_view, about, mission, blog

urlpatterns = [
    path('', home, name='home'),
    path('team/', team_view, name='team'),
    path('about/', about, name='about'),
    path('mission/', mission, name='mission'),
    path('blog/', blog, name='blog'),

    
]

user/urls.py
# user/urls.py
from django.urls import path
from .views import signup, signin, signout, create_profile, profile, edit_profile, verify_otp
from django.urls import path
from . import views 



app_name = 'user'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('signin/', signin, name='signin'),
    path('signout/', signout, name='signout'),
    path('create_profile/', create_profile, name='create_profile'),
    path('profile/', profile, name='profile'),
    path('edit-profile/', edit_profile, name='edit_profile'), 
    path('verify_otp/', verify_otp, name='verify_otp'),


]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from allauth.socialaccount.models import SocialAccount

class University(models.Model):
    name = models.CharField(max_length=100)
    state = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class College(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class CustomUser(AbstractUser):
    email = models.EmailField(unique=False)


    def __str__(self):
        return self.email  

class UserProfile(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]

    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30, null=True, blank=True)  # Last name is not compulsory
    date_of_birth = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True, blank=True)
    bio = models.TextField(max_length=50, null=True, blank=True)
    university = models.ForeignKey(University, on_delete=models.SET_NULL, null=True, blank=True)
    college = models.ForeignKey(College, on_delete=models.SET_NULL, null=True, blank=True)
    registration_id = models.CharField(max_length=20, blank=False)
    course = models.CharField(max_length=50, blank=False)
    department = models.CharField(max_length=50, blank=False)
    profile_picture = models.ImageField(upload_to='profile_pics/')

    # New fields
    graduation_year = models.PositiveIntegerField(blank=True, null=True)
    website = models.URLField(max_length=200, blank=True, null=True)
    github = models.URLField(max_length=200, blank=True, null=True)
    linkedin = models.URLField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.user.username

# Signal to create UserProfile instance upon creation of CustomUser instance
@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

user/forms.py
# from django import forms
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth import get_user_model
# from .models import UserProfile

# CustomUser = get_user_model()

# class SignUpForm(UserCreationForm):
#     class Meta:
#         model = CustomUser
#         fields = ('username', 'password1', 'password2')

# class SignInForm(forms.Form):
#     username = forms.CharField(label='Username')
#     password = forms.CharField(label='Password', widget=forms.PasswordInput)

# class UserProfileForm(forms.ModelForm):
#     class Meta:
#         model = UserProfile
#         fields = ['first_name', 'last_name', 'date_of_birth', 'gender', 'bio', 'university_name', 'college_name', 'registration_id', 'department', 'course', 'profile_picture']
#         widgets = {
#             'date_of_birth': forms.DateInput(attrs={'type': 'date'}),
#         }

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         placeholders = {
#             'first_name': 'Enter your first name',
#             'last_name': 'Enter your last name',
#             'date_of_birth': 'Select your date of birth',
#             'gender': 'Select your gender',
#             'bio': 'Write a brief bio (max 50 words)',
#             'university_name': 'Enter your university name',
#             'college_name': 'Enter your college name',
#             'registration_id': 'Enter your registration ID',
#             'course': 'Enter your course',
#             'department': 'Enter your department',
#             'profile_picture': 'Upload your profile picture',
#         }

#         for field in self.fields:
#             self.fields[field].widget.attrs['placeholder'] = placeholders[field]

















# user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import UserProfile

CustomUser = get_user_model()

class SignUpForm(UserCreationForm):
    # email = forms.EmailField(label='Email', widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.', label='Email', widget=forms.TextInput(attrs={'id': 'id_email_signup', 'placeholder': 'Email'}))  

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))

    class Meta:
        model = CustomUser
        fields = ('email', 'password1', 'password2')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

class SignInForm(forms.Form):
    email = forms.EmailField(label='', widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    password = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Add additional styles to specific fields
        self.fields['email'].widget.attrs['class'] = 'custom-email-field'
        self.fields['password'].widget.attrs['class'] = 'custom-password-field'

from django import forms
from .models import UserProfile

from django import forms
from .models import UserProfile, University, College

class UserProfileForm(forms.ModelForm):
    university_name = forms.ModelChoiceField(queryset=University.objects.all(), empty_label="Select your university")
    college_name = forms.ModelChoiceField(queryset=College.objects.all(), empty_label="Select your college")

    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'date_of_birth', 'gender', 'bio', 'university_name', 'college_name', 'registration_id', 'department', 'course', 'profile_picture']
        widgets = {
            'date_of_birth': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        placeholders = {
            'first_name': 'Enter your first name',
            'last_name': 'Enter your last name',
            'date_of_birth': 'Select your date of birth',
            'gender': 'Select your gender',
            'bio': 'Write a brief bio (max 50 words)',
            'registration_id': 'Enter your registration ID',
            'course': 'Enter your course',
            'department': 'Enter your department',
            'profile_picture': 'Upload your profile picture',
        }

        for field in self.fields:
            self.fields[field].widget.attrs['placeholder'] = placeholders.get(field, '')

        # Set required attribute for all fields except last_name
        for field_name, field in self.fields.items():
            if field_name != 'last_name':
                field.required = True

user/templates/create_profile.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}" />
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet" />


<link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />

<script src="https://apis.google.com/js/platform.js" async defer></script>
<!-- Include Google's official CSS for the sign-in button -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">





{% comment %} <body class="custom-body-profile">

    <nav class="navbar">
        <div class="logo">
            <a href="{% url 'home' %}">
                <img src="{% static 'images/logo.jpg' %}" alt="Logo" class="logo-image">
            </a>
        </div>
    </nav>

    <div class="create-profile-content">
        <form method="post" enctype="multipart/form-data" class="custom-form">
            {% csrf_token %}
            <h2 class="custom-h2">Create Your Profile</h2>
            
            <section class="custom-section">
                <label for="{{ form.first_name.id_for_label }}" class="custom-label">First Name:</label>
                {{ form.first_name }}
                
                <label for="{{ form.last_name.id_for_label }}" class="custom-label">Last Name:</label>
                {{ form.last_name }}
                
                <label for="{{ form.date_of_birth.id_for_label }}" class="custom-label">Date of Birth:</label>
                {{ form.date_of_birth }}
                
                <label for="{{ form.gender.id_for_label }}" class="custom-label">Gender:</label>
                {{ form.gender }}
            </section>
            
            <section class="custom-section">
                <label for="{{ form.bio.id_for_label }}" class="custom-label">Bio (max 50 words):</label>
                {{ form.bio }}

                <label for="{{ form.university_name.id_for_label }}" class="custom-label">University Name:</label>
                {{ form.university_name }}
                
                <label for="{{ form.college_name.id_for_label }}" class="custom-label">College Name:</label>
                {{ form.college_name }}
                
            </section>
            
            <section class="custom-section">
                <label for="{{ form.registration_id.id_for_label }}" class="custom-label">Registration ID:</label>
                {{ form.registration_id }}

                <label for="{{ form.course.id_for_label }}" class="custom-label">Course:</label>
                {{ form.course }}
                
                <label for="{{ form.department.id_for_label }}" class="custom-label">Department:</label>
                {{ form.department }}

                <label for="{{ form.profile_picture.id_for_label }}" class="custom-label">Profile Picture:</label>
                {{ form.profile_picture }}
            </section>
            
            <button type="submit" class="custom-button">Submit</button>
        </form>
    </div>
</body> {% endcomment %}


<body class="custom-body-profile">      
      
    <nav class="navbar">
        <div class="logo">
            <a href="{% url 'home' %}">
                <img src="{% static 'images/logo.jpg' %}" alt="Logo" class="logo-image">
            </a>
        </div>
        
        <div class="navbar-links">

            <div class="notification-home">
                <a href="{% url 'home' %}">
                    <i class="material-icons" style="font-size: 1.8rem; margin-top:-3px;">home</i>
                </a>
            </div>

            <div class="dropdown">
                {% if user.is_authenticated %}
                    <div class="user-profile">
                        {% if user.userprofile.profile_picture %}
                            <img src="{{ user.userprofile.profile_picture.url }}" alt="Profile Picture" class="profile-picture">
                        {% else %}
                            <img src="{% static 'images/default_profile/Gemini_Generated_Image (39).jpg' %}" alt="Default Profile Picture" class="profile-picture">
                        {% endif %}
                    </div>
                        
                {% else %}
                    <a class="login-text" href="{% url 'user:signin' %}">Login</a>
                {% endif %}
    
                {% if user.is_authenticated %}
                    <div class="dropdown-content" style="margin-left:-40px;">
                        <a href="{% url 'user:signout' %}">Logout</a>
                    </div>
                {% else %}
                    <div class="dropdown-content" style="margin-left:-40px;">
                        <a href="{% url 'user:signin' %}">Login</a>
                        <a href="{% url 'user:signup' %}">Signup</a>
                    </div>
                {% endif %}
            </div>  
        </div>
    </nav>
    <h2 class="custom-h2">Create Your Profile</h2>

    <div class="create-profile-content">

        <form method="post" enctype="multipart/form-data" class="custom-form">
            {% csrf_token %}
            
            <div class="custom-section">
                <label for="id_first_name" class="custom-label">First Name: {{ form.first_name }}</label>

                <label for="id_last_name" class="custom-label">Last Name: {{ form.last_name }}</label>

                <label for="id_date_of_birth" class="custom-label">Date of Birth: {{ form.date_of_birth }}</label>

                <label for="id_gender" class="custom-label">Gender: {{ form.gender }}</label>
            </div>

            <div class="custom-section">
                <label for="id_bio" class="custom-label">Bio (max 50 words): {{ form.bio }}</label>

                <label for="id_university_name" class="custom-label">University Name: {{ form.university_name }}</label>

                <label for="id_college_name" class="custom-label">College Name: {{ form.college_name }}</label>
            </div>

            <div class="custom-section">
                <label for="id_registration_id" class="custom-label">Registration ID: {{ form.registration_id }}</label>

                <label for="id_course" class="custom-label">Course: {{ form.course }}</label>

                <label for="id_department" class="custom-label">Department: {{ form.department }}</label>

                {% comment %} <label for="id_profile_picture" class="custom-label">Profile Picture: {{ form.profile_picture }}</label> {% endcomment %}
            
                <div class="profile-picture-wrapper">
                    {% comment %} {{ form.profile_picture }} {% endcomment %}

                    <label for="id_profile_picture" class="custom-label">Profile Picture: {{ form.profile_picture }}</label>

                </div>

            
            </div>
            
            <button type="submit" class="custom-button">Submit</button>
        </form>


        

    </div>
</body>

user/templates/otp.html
{% load static %}
{% load socialaccount %}

<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet" />


<link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />

<script src="https://apis.google.com/js/platform.js" async defer></script>
<!-- Include Google's official CSS for the sign-in button -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">


    <body class="main-body-signin">

        <nav class="navbar">
            <div class="logo">
                <a href="{% url 'home' %}">
                    <img src="{% static 'images/logo.jpg' %}" alt="Logo" class="logo-image">
                </a>
            </div>
            
            <div class="navbar-links">

                <a href="{% url 'home' %}">
                <div class="navbar-icons-signin">
                    <div class="home-icon icon-home">
                        <i class="material-icons icon-home" style="font-size: 1.8rem;">home</i>
                    </div>
                </div>
                </a>
            </div>
        </nav>

            {% comment %} <div class="otp-main" style="margin-top:100px; color:black; background-color:yellow;">
                <p>Sign Up</p>
                <hr>
                <p>Verify Email</p>
                <div class="otp-content">
                    <p>Enter the One Time Password sent to your Email</p>
                    <form method="post">
                        {% csrf_token %}
                        <label for="otp1">OTP:</label><br>
                        <input type="text" id="otp1" name="otp1" maxlength="1" size="1" pattern="[0-9]" required>
                        <input type="text" id="otp2" name="otp2" maxlength="1" size="1" pattern="[0-9]" required>
                        <input type="text" id="otp3" name="otp3" maxlength="1" size="1" pattern="[0-9]" required>
                        <input type="text" id="otp4" name="otp4" maxlength="1" size="1" pattern="[0-9]" required><br>
                        <button type="submit">Verify OTP</button>
                    </form>
                </div>
            </div> {% endcomment %}

            
            <div class="otp-main">
                <p>Sign Up</p>
                <hr>
                <p class="verify-otp">Verify Email</p>
                <div class="otp-content">
                    <p>Enter the One Time Password sent to your Email</p>
                    <form id="otpForm" method="post">
                        {% csrf_token %}
                        <label for="otp1"></label><br>
                        <input type="text" id="otp1" name="otp1" maxlength="1" size="1" pattern="[0-9]" required>
                        <input type="text" id="otp2" name="otp2" maxlength="1" size="1" pattern="[0-9]" required>
                        <input type="text" id="otp3" name="otp3" maxlength="1" size="1" pattern="[0-9]" required>
                        <input type="text" id="otp4" name="otp4" maxlength="1" size="1" pattern="[0-9]" required><br>
                        <div id="otpStatus"></div> <!-- Display area for OTP status -->
                        <button type="button" id="verifyButton">Continue</button>
                    </form>
                </div>
            </div>
            

            {% comment %} 
            <script>
                document.getElementById('verifyButton').addEventListener('click', function() {
                    var otpEntered = document.getElementById('otp1').value +
                                     document.getElementById('otp2').value +
                                     document.getElementById('otp3').value +
                                     document.getElementById('otp4').value;
            
                    var otpStatus = document.getElementById('otpStatus');
                    otpStatus.innerHTML = '<span style="color:blue;">Verifying OTP...</span>';
            
                    // Simulate OTP verification (replace with actual AJAX call)
                    setTimeout(function() {
                        var otpSaved = "{{ request.session.otp }}"; // Replace with actual OTP from session
            
                        if (otpEntered === otpSaved) {
                            otpStatus.innerHTML = '<span style="color:green;"><i class="fas fa-check"></i> Verified</span>';
                            // Perform necessary actions upon successful verification (e.g., enable form submission)
                            document.getElementById('otpForm').submit();
            
                            // Clear the status message after 3 seconds
                            setTimeout(function() {
                                otpStatus.innerHTML = ''; // Clear the status message
                            }, 3000);
                        } else {
                            otpStatus.innerHTML = '<span style="color:red;"><i class="fas fa-times"></i> Oops! You have entered the wrong OTP. Please try again.</span>';
            
                            // Clear the error message after 3 seconds
                            setTimeout(function() {
                                otpStatus.innerHTML = ''; // Clear the error message
                            }, 3000);
                        }
                    }, 2000); // Simulate OTP verification delay
                });
            </script>
            
             {% endcomment %}


             <style>
                /* Define keyframes for loading animation */
                @keyframes spin {
                    0% { transform: rotate(0deg); }
                    100% { transform: rotate(360deg); }
                }
            
                /* Styling for loading spinner */
                .loader {
                    border: 4px solid rgba(0, 0, 0, 0.1);
                    border-top: 4px solid black;
                    border-radius: 50%;
                    width: 20px;
                    height: 20px;
                    animation: spin 1s linear infinite;
                    display: inline-block;
                    vertical-align: middle;
                }
            </style>
            <script>
                document.getElementById('verifyButton').addEventListener('click', function() {
                    var otpEntered = document.getElementById('otp1').value +
                                     document.getElementById('otp2').value +
                                     document.getElementById('otp3').value +
                                     document.getElementById('otp4').value;
            
                    var otpStatus = document.getElementById('otpStatus');
                    otpStatus.innerHTML = '<span style="color:blue;">Verifying OTP... <span class="loader"></span></span>';
            
                    // Simulate OTP verification (replace with actual AJAX call)
                    setTimeout(function() {
                        var otpSaved = "{{ request.session.otp }}"; // Replace with actual OTP from session
            
                        if (otpEntered === otpSaved) {
                            otpStatus.innerHTML = '<span style="color:green;"><i class="fas fa-check"></i> Verified</span>';
                            // Perform necessary actions upon successful verification (e.g., enable form submission)
                            document.getElementById('otpForm').submit();
            
                            // Clear the status message after 3 seconds
                            setTimeout(function() {
                                otpStatus.innerHTML = ''; // Clear the status message
                            }, 3000);
                        } else {
                            otpStatus.innerHTML = '<span style="color:red;"><i class="fas fa-times"></i> Oops! You have entered the wrong OTP. Please try again.</span>';
            
                            // Clear the error message after 3 seconds
                            setTimeout(function() {
                                otpStatus.innerHTML = ''; // Clear the error message
                            }, 3000);
                        }
                    }, 2000); // Simulate OTP verification delay
                });
            </script>
            

            

    </body> 