home/urls.py
# home/urls.py
from django.urls import path
from .views import home, team_view, about, mission, blog

urlpatterns = [
    path('', home, name='home'),
    path('team/', team_view, name='team'),
    path('about/', about, name='about'),
    path('mission/', mission, name='mission'),
    path('blog/', blog, name='blog'),

    
]

social/urls.py
from django.urls import path
from .views import create_group, search_group, join_group, group_detail, feeds_view, create_post

app_name = 'social'

urlpatterns = [
    path('create_group/', create_group, name='create_group'),
    path('search_group/', search_group, name='search_group'),
    path('join_group/<str:group_id>/', join_group, name='join_group'),
    path('social/group_detail/<str:group_id>/', group_detail, name='group_detail'),
    path('feeds/', feeds_view, name='feeds_view'),
    path('create_post/', create_post, name='create_post'),
]

social/models.py
import uuid
from django.db import models
from user.models import CustomUser


def generate_unique_group_id():
    return uuid.uuid4().hex[:10]


class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    group_id = models.CharField(max_length=10, unique=True, default=generate_unique_group_id)
    description = models.TextField()
    members = models.ManyToManyField(CustomUser, related_name='group_members', blank=True)
    creator = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='group_creator')
    tags = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name





from django.db import models
from user.models import CustomUser
from social.models import Group

class Post(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    groups = models.ManyToManyField(Group, related_name='group_post', blank=True)  # Fix the related_name
    caption = models.TextField()
    post_type = models.CharField(max_length=20, choices=[('normal', 'Normal Post'), ('event', 'Event')])
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.created_at}"

social/forms.py
from django import forms
from .models import Group, Post


from django import forms
from .models import Group
from taggit.forms import TagField


from django import forms
from .models import Group

class GroupCreationForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name', 'description', 'tags']



class GroupSearchForm(forms.Form):
    search_query = forms.CharField(label='Search Group')


class GroupJoinForm(forms.Form):
    group_id = forms.CharField(label='Group ID')


# class PostCreationForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = ['caption', 'post_type', 'image']
        
# social/forms.py

class PostCreationForm(forms.ModelForm):
    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.none(), widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-check-input'}))

    class Meta:
        model = Post
        fields = ['caption', 'post_type', 'image', 'groups']

    def __init__(self, user, *args, **kwargs):
        super(PostCreationForm, self).__init__(*args, **kwargs)
        self.fields['groups'].queryset = user.group_members.all()

social/views.py
# social/views.py
from django.shortcuts import render
from django.urls import reverse
from django.shortcuts import render, redirect
from .models import Group
from .forms import GroupCreationForm, GroupSearchForm
from user.models import UserProfile
from django.contrib.auth.decorators import login_required




# @login_required
# def create_group(request):
#     group_id = None

#     if request.method == 'POST':
#         form = GroupCreationForm(request.POST)
#         if form.is_valid():
#             group = form.save(commit=False)
#             group.creator = request.user
#             group.save()
#             group.members.add(request.user)
#             # Get the group_id after saving the form
#             group_id = group.group_id

#             # Redirect to the 'group_detail' view with the correct group_id
#             return redirect('social:group_detail', group_id=group_id)

#     else:
#         form = GroupCreationForm()
#     return render(request, 'create_group.html', {'form': form, 'group_id': group_id})


from django.shortcuts import render, redirect
from .models import Group
from .forms import GroupCreationForm
from django.contrib.auth.decorators import login_required

# social/views.py
from django.shortcuts import render, redirect
from .models import Group
from .forms import GroupCreationForm
from django.contrib.auth.decorators import login_required

@login_required
def create_group(request):
    group_id = None

    if request.method == 'POST':
        form = GroupCreationForm(request.POST)
        if form.is_valid():
            group = form.save(commit=False)
            group.creator = request.user
            group.save()
            group.members.add(request.user)
            # Save tags
            tags = form.cleaned_data.get('tags')
            if tags:
                # Split tags by comma and strip whitespace
                tag_list = [tag.strip() for tag in tags.split(',')]
                # Add tags to the group
                group.tags = ','.join(tag_list)
                group.save()

            # Get the group_id after saving the form
            group_id = group.group_id
            # Redirect to the 'group_detail' view with the correct group_id
            return redirect('social:group_detail', group_id=group_id)

    else:
        form = GroupCreationForm()
    return render(request, 'create_group.html', {'form': form, 'group_id': group_id})



@login_required
def search_group(request):
    user_groups = []

    if request.user.is_authenticated:
        user_groups = request.user.group_members.all()

    search_results = []

    if request.method == 'POST':
        form = GroupSearchForm(request.POST)
        if form.is_valid():
            search_query = form.cleaned_data['search_query']

            groups = Group.objects.filter(group_id__exact=search_query)

            for group in groups:
                already_member = group in user_groups
                search_results.append((group, already_member))
    else:
        form = GroupSearchForm()

    return render(request, 'search_group.html', {'form': form, 'search_results': search_results, 'user_groups': user_groups})

@login_required
def join_group(request, group_id):
    group = Group.objects.get(group_id=group_id)
    group.members.add(request.user)
    return redirect('social:group_detail', group_id=group.group_id)


# social/views.py

@login_required
def group_detail(request, group_id):
    group = Group.objects.get(group_id=group_id)
    user_groups = request.user.group_members.all()

    # Use reverse with the app name and URL pattern name
    group_detail_url = reverse('social:group_detail', args=[group_id])

    return render(request, 'group_detail.html', {'group': group, 'user_groups': user_groups, 'group_detail_url': group_detail_url})


from .models import Group

# def feeds_view(request):
#     # Retrieve the user's profile
#     try:
#         user_profile = UserProfile.objects.get(user=request.user)
#     except UserProfile.DoesNotExist:
#         user_profile = None

#     # Retrieve the user's groups
#     user_groups = Group.objects.filter(members=request.user)

#     return render(request, 'feeds.html', {'user': request.user, 'user_profile': user_profile, 'user_groups': user_groups})

# social/views.py

from django.shortcuts import render
from .models import Post
from user.models import UserProfile
@login_required
def feeds_view(request):
    # Retrieve the user's profile
    try:
        user_profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        user_profile = None
    
    # Retrieve the user's groups
    user_groups = Group.objects.filter(members=request.user)

    # Retrieve all posts of the current user
    user_posts = Post.objects.filter(user=request.user).order_by('-created_at')

    return render(request, 'feeds.html', {'user': request.user, 'user_profile': user_profile, 'user_posts': user_posts, 'user_groups': user_groups})






from django.shortcuts import render, redirect
from .forms import GroupCreationForm, GroupSearchForm, GroupJoinForm, PostCreationForm
from .models import Group, Post
from user.models import UserProfile

from django.contrib import messages


# from .forms import PostCreationForm


# def create_post(request):
#     if request.method == 'POST':
#         post_form = PostCreationForm(request.user, request.POST, request.FILES)
#         if post_form.is_valid():
#             post = post_form.save(commit=False)
#             post.user = request.user
#             post.save()

#             messages.success(request, 'Post successfully created!')
#             return redirect('social:feeds')
#     else:
#         post_form = PostCreationForm(user=request.user)  # Pass the user to the form

#     try:
#         user_profile = UserProfile.objects.get(user=request.user)
#     except UserProfile.DoesNotExist:
#         user_profile = None

#     user_groups = Group.objects.filter(members=request.user)
#     user_posts = Post.objects.filter(user__in=user_groups.values_list('members', flat=True)).order_by('-created_at')

#     return render(request, 'feeds.html', {'user': request.user, 'user_profile': user_profile, 'user_groups': user_groups, 'user_posts': user_posts, 'post_form': post_form})

from django.shortcuts import render, redirect
from .forms import PostCreationForm
from .models import Post
from django.contrib import messages
from user.models import UserProfile
from .models import Group  

from django.shortcuts import render, redirect
from .forms import PostCreationForm
from .models import Post
from django.contrib import messages
from user.models import UserProfile
from .models import Group 
 
@login_required
def create_post(request):
    user_groups = Group.objects.filter(members=request.user)

    if request.method == 'POST':
        post_form = PostCreationForm(request.user, request.POST, request.FILES)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()
            post.groups.set(post_form.cleaned_data['groups'])

            # Debugging: Print post information
            print(f"Post created - ID: {post.id}, Caption: {post.caption}, User: {post.user.username}")

            # Print associated groups
            print("Associated Groups:")
            for group in post.groups.all():
                print(f"- {group.name}")

            messages.success(request, 'Post successfully created!')

            # Redirect to the feeds page
            return redirect('social:feeds_view')

    post_form = PostCreationForm(user=request.user)
    user_profile = UserProfile.objects.get(user=request.user) if UserProfile.objects.filter(user=request.user).exists() else None

    # Retrieve the user's posts
    user_posts = Post.objects.filter(user=request.user).order_by('-created_at')

    # Debugging: Print user posts
    print("User Posts:")
    for user_post in user_posts:
        print(f"- {user_post.id} - {user_post.caption}")

    return render(request, 'feeds.html', {'user': request.user, 'user_profile': user_profile, 'user_groups': user_groups, 'user_posts': user_posts, 'post_form': post_form})

social/templates/create_group.html
{% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet" />
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>





<div class="creategroup-popup creategroup-main">

    <h2>Create Group</h2>

    <div class="creategroup-coverimg">
        <img>
    <div>

    <div class="form">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="{{ form.name.id_for_label }}">Group Name:</label>
            {{ form.name }}
            <label for="{{ form.description.id_for_label }}">Group Description:</label>
            {{ form.description }}
            <label for="id_tags">Tags (separated by commas):</label>
            <input type="text" id="id_tags" name="tags">
            <button type="submit">Create</button>
        </form>
    </div>
</div>





















    <br><br>
    <p style="margin-top: 20px;">
        <a href="{% url 'social:search_group' %}"><button>Search Groups</button></a>
        {% if group_id %}
            <a href="{% url 'social:group_detail' group_id=group_id %}"><button>View Created Group</button></a>
        {% endif %}
    
    </p>

social/templates/groupSearchAndList.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="groupSearchAndList.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

</head>
<body>
  <div class="gslpage" style="background-color: grey;height:100vh;">

    
    <!-- navbar -->
    <div class="navpg1" style="background-color: grey;">
        <div class="navbarpg1">
          <div class="leftnavpg1">
              <img src="img1.jpg" alt="logo..." style="margin-right: 1.5vw; ">
              <h3>College Connect</h3>
          </div>
          
  
          <div class="rightnavpg1">
              <input type="text" style="padding-inline: 2vw; border-radius: 1rem; height: 3.5vh;width:15vw; border:none;">
              <i class="fas fa-search"></i>
              <i class="fa-solid fa-bell" style="margin-right: 1vw; color:white; font-size:1.5vw; cursor: pointer;"></i>
              <img src="img1.jpg" alt="dp...">
          </div>
        </div>
      </div>
      <!-- Navbar end -->

      <h1 style="margin:1vh 2.5vw; font-size: 2.3rem;">Groups</h1>
      <div class="gsl" style="display:flex;justify-content:space-evenly;">
        <div class="gslcol1">
            <div class="gslc1row">
                <p>Joined Groups</p>
                <div class="gslcards">
                    <div class="gslcard">
                        <img src="img1.jpg" alt="">
                        <div class="gslcardgrpname">
                            <i class="fa-solid fa-user-group grpicon"></i>
                            <p>Group name</p>
                        </div>
                        <p>80,000 members</p>
                        <div class="gslcardsymbolscol1">
                            <i class="fa-solid fa-bell" style="margin-right: 1vw; cursor: pointer;"></i>
                            <i class="fa-sharp fa-solid fa-volume-xmark"></i>
                            <i class="fa-solid fa-trash-can"></i>
                        </div>
                    </div>
                    <div class="gslcard">
                        <img src="img1.jpg" alt="">
                        <div class="gslcardgrpname">
                            <i class="fa-solid fa-user-group grpicon"></i>
                            <p>Group name</p>
                        </div>
                        <p>80,000 members</p>
                        <div class="gslcardsymbolscol1">
                            <i class="fa-solid fa-bell" style="margin-right: 1vw; cursor: pointer;"></i>
                            <i class="fa-sharp fa-solid fa-volume-xmark"></i>
                            <i class="fa-solid fa-trash-can"></i>
                        </div>
                    </div>
                    <div class="gslcard">
                        <img src="img1.jpg" alt="">
                        <div class="gslcardgrpname">
                            <i class="fa-solid fa-user-group grpicon"></i>
                            <p>Group name</p>
                        </div>
                        <p>80,000 members</p>
                        <div class="gslcardsymbolscol1">
                            <i class="fa-solid fa-bell" style="margin-right: 1vw; cursor: pointer;"></i>
                            <i class="fa-sharp fa-solid fa-volume-xmark"></i>
                            <i class="fa-solid fa-trash-can"></i>
                        </div>
                    </div>
                    <div class="gslcard">
                        <img src="img1.jpg" alt="">
                        <div class="gslcardgrpname">
                            <i class="fa-solid fa-user-group grpicon"></i>
                            <p>Group name</p>
                        </div>
                        <p>80,000 members</p>
                        <div class="gslcardsymbolscol1">
                            <i class="fa-solid fa-bell" style="margin-right: 1vw; cursor: pointer;"></i>
                            <i class="fa-sharp fa-solid fa-volume-xmark"></i>
                            <i class="fa-solid fa-trash-can"></i>
                        </div>
                    </div>
                    
                </div>
            </div>
            <div class="gslc1row">
                <p>Created Groups</p>
                <div class="gslcards">
                    <div class="gslcard">
                        <img src="img1.jpg" alt="">
                        <div class="gslcardgrpname">
                            <i class="fa-solid fa-user-group grpicon"></i>
                            <p>Group name</p>
                        </div>
                        <p>80,000 members</p>
                        <div class="gslcardsymbolscol1">
                            <i class="fa-solid fa-bell" style="margin-right: 1vw; cursor: pointer;"></i>
                            <i class="fa-sharp fa-solid fa-volume-xmark"></i>
                            <i class="fa-solid fa-trash-can"></i>
                        </div>
                    </div>
                    <div class="gslcard">
                        <img src="img1.jpg" alt="">
                        <div class="gslcardgrpname">
                            <i class="fa-solid fa-user-group grpicon"></i>
                            <p>Group name</p>
                        </div>
                        <p>80,000 members</p>
                        <div class="gslcardsymbolscol1">
                            <i class="fa-solid fa-bell" style="margin-right: 1vw; cursor: pointer;"></i>
                            <i class="fa-sharp fa-solid fa-volume-xmark"></i>
                            <i class="fa-solid fa-trash-can"></i>
                        </div>
                    </div>
                    <div class="gslcard">
                        <img src="img1.jpg" alt="">
                        <div class="gslcardgrpname">
                            <i class="fa-solid fa-user-group grpicon"></i>
                            <p>Group name</p>
                        </div>
                        <p>80,000 members</p>
                        <div class="gslcardsymbolscol1">
                            <i class="fa-solid fa-bell" style="margin-right: 1vw; cursor: pointer;"></i>
                            <i class="fa-sharp fa-solid fa-volume-xmark"></i>
                            <i class="fa-solid fa-trash-can"></i>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="gslcol2" style="width:25%; height:80vh;">
            <div class="searchgrpspg1" style="padding:2vw 3vw;margin-bottom:2vh;background-color: pink; border-radius: 1rem;">
                <p style="font-size:1.5rem;margin-left: 0.3vw;margin-bottom: 2vh;">Search Groups</p>
                <input type="text" placeholder="Enter the group code" style="border-radius:3rem; padding:2vh;width:90%; margin-bottom:2vh;">
                <div class="grpnamecol3pg1" style="border:2px solid black;display:flex;align-items: center;border-radius: 3rem;padding-top:0.5vh;padding-bottom:0.5vh;justify-content: space-between;margin-bottom:3vh;">
                  <i class="fa-solid fa-user-group grpicon" style="width:2vw;height:2vw;font-size: 1.5vw;" ></i>
                  <p>Group Name</p>
                  <button style="background-color: red;width:5vw; height:5vh;border-radius:3rem;font-weight: bold;margin-right: 0.3vw;">Join</button>
                </div>
            </div>

            <div class="creategrppg1" style="background-color: pink; border-radius: 1rem;text-align: center;padding:2vw; margin-bottom:2vh;">
                <button id="open-modal" style="background-color: red;width:15vw; height:6vh;border-radius:3rem;font-weight: bold;">Create Group</button>
                <!-- Vertically centered modal -->
                <div id="myModal" class="modal">
                  <div class="modal-content">
                    <div class="modal1pg1">
                      <h2 style="margin-bottom:2vh;margin-left:-1vw;">Create Group</h2>
                      <span class="close">&times;</span>
                    </div>
                    <div class="covermodalpg1" style="width:100%; height:25vh;background-color: red;border-radius: 1rem;position:relative;">
                      <!-- coverimage and other contents inside it -->
                      <img src="dpimg.jpg" alt="" style="width:100%;height:100%;border-radius:1rem;position:relative;">
                      <div class="dpimgmodalpg1" style="position:absolute; right:50vw;top:8vw;">
                        <div style="position: relative; display: inline-block;">
                        <img src="img1.jpg" alt="" style="width:4vw;height:4vw;border-radius:5rem;">
                        <i class="fa-sharp fa-solid fa-pen" style="position: absolute; right: -0.6vw; top: 2.5vw;border-radius:5rem;color:rgb(50, 179, 222);width:2vw;height:2vw;"></i>
                        </div>
                      </div>
                      
                    </div>
    
                    <i class="fa-sharp fa-solid fa-pen" style="position: absolute; right: 23.4vw; top: 12vw;border-radius:5rem;color:rgb(50, 179, 222);width:2vw;height:2vw;"></i>
    
                    <div class="grpnametagsmodalpg1" style="display: flex; align-items: center; justify-content: space-between;padding:1vw;">
                      <div class="grpnamemmodalpg1">
                        <p>Group Name*</p>
                        <input type="text">
                      </div>
                      <div class="tagsmodalpg1">
                        <p>Tags*</p>
                        <input type="text">
                      </div>
                    </div>
    
                    <div class="descriptionbuttonmodalpg1" style="display:flex; justify-content: space-between; align-items: center;padding:1vw;">
                      <div class="descmodalpg1" style="display:flex;flex-direction: column;text-align: start;">
                        <p>Group Description*</p>
                        <input type="text" style="border-radius:1rem; height:20vh;width:24vw;margin-top: 0.8vh;">
                      </div>
                      <div class="buttonmodalpg1" style="display:flex;align-items: center; justify-content: center;padding-right:7vw;">
                        <button style="background-color: red;width:12vw; height:6vh;border-radius:1rem;font-weight: bold;font-size: 1.2rem;">Create</button>
                      </div>
                    </div>
    
                  </div>
                </div>
              </div>
    
    
              
        </div>
      </div>
    </div>

    <script>
        // Get the modal
        var modal = document.getElementById("myModal");
        
        // Get the button that opens the modal
        var btn = document.getElementById("open-modal");
        
        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("close")[0];
        
        
        
        // When the user clicks the button, open the modal 
        btn.onclick = function() {
          modal.style.display = "block";
        }
        
        // When the user clicks on <span> (x) or the close button inside the modal, close the modal
        span.onclick = function() {
          modal.style.display = "none";
        }
        
        
        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
          if (event.target == modal) {
            modal.style.display = "none";
          }
        }
        
        
    </script>
</body>
</html>

social/templates/group_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <style>
        body {
            background-color: #001735;
            color: #fff;
            font-family: 'Arial', sans-serif;

        }
        .details{
            background-color: #001735;
            color: #fff;
            font-family: 'Arial', sans-serif;
            display: flex;
            justify-content: space-around;
            align-items: flex-start;
        }
        .group-details,
        .user-groups {
            width: 48%;
            padding: 20px;
            box-sizing: border-box;
        }

        .group-details {
            border-right: 2px solid #ff3131;
        }

        h2,
        h3 {
            color: #fff;
            
        }

        p {
            margin-bottom: 20px;
            color: #fff;
        }

        form {
            margin-top: 20px;
        }

        button {
            background-color: #ff3131;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        button:hover {
            background-color: #001735;
        }

        ul {
            list-style: none;
            padding: 0;
        }

        li {
            margin: 10px 0;
        }

        a {
            color: #fff;
            text-decoration: none;

        }

        a:hover {
            text-decoration: underline;
        }

        #group-id {
            display: none;
            margin-top: 20px;
        }
    </style>
<div class="details">
    <div class="group-details">
        <h2>{{ group.name }}</h2>
        <p>{{ group.description }}</p>

        {% if user.is_authenticated %}
            {% if user in group.members.all %}
                <p>You are already a member of this group.</p>
                <button onclick="showGroupId()">Invite Friends</button>
                <div id="group-id">
                    <p>Share this group ID with your friends: {{ group.group_id }}</p>
                </div>
            {% else %}
                <form method="post" action="{% url 'join_group' group_id=group.group_id %}">
                    {% csrf_token %}
                    <button type="submit">Join Group</button>
                </form>
            {% endif %}
        {% else %}
            <p>Login to join this group.</p>
        {% endif %}

        <h3>Group Members:</h3>
        <ul>
            {% for member in group.members.all %}
                <li>{{ member.username }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="user-groups">
        <h2>Your Groups</h2>

        <h3>Groups Joined:</h3>
        <ul>
            {% for joined_group in user_groups %}
                <li><a href="{% url 'social:group_detail' group_id=joined_group.group_id %}">{{ joined_group.name }}</a></li>
            {% endfor %}
        </ul>

        <br><br>
        <p>
            <a href="{% url 'social:create_group' %}"><button>Create a Group</button></a>
            <a href="{% url 'social:search_group' %}"><button>Search Groups</button></a>
        </p>
    </div>
</div>

    <script>
        function showGroupId() {
            var groupIdDiv = document.getElementById('group-id');
            groupIdDiv.style.display = 'block';
        }
    </script>

{% endblock %}

social/templates/search_group.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <style>
        body {
            background-color: #001735;
            color: #fff;
            font-family: 'Arial', sans-serif;
            text-align: center;
        }

        h2,
        h3 {
            color: #ff3131;
        }

        form {
            margin: 20px auto;
            padding: 20px;
            background-color: #000;
            border-radius: 10px;
            max-width: 300px;
        }

        label {
            color: #fff;
            display: block;
            margin-bottom: 8px;
        }

        input[type="text"] {
            width: calc(100% - 22px);
            padding: 10px;
            margin-bottom: 12px;
            box-sizing: border-box;
            background-color: #fff;
            color: #000;
            border: none;
            border-radius: 5px;
        }

        button {
            background-color: #ff3131;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        button:hover {
            background-color: #001735;
        }

        ul {
            list-style: none;
            padding: 0;
        }

        li {
            margin: 10px 0;
        }

        a {
            color: #ff3131;
            text-decoration: none;
        }

        a:hover {
            text-decoration: underline;
        }
    </style>

    <h2>Search Groups</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Search</button>
    </form>

    {% if user.is_authenticated %}
        <div style="display: flex; justify-content: space-around;">
            <div style="width: 48%;">
                <h3>Your Groups:</h3>
                <ul>
                    {% for joined_group in user_groups %}
                        <li><a href="{% url 'social:group_detail' group_id=joined_group.group_id %}">{{ joined_group.name }}</a></li>
                    {% endfor %}
                </ul>
                <br>
                <p><a href="{% url 'social:create_group' %}"><button>Create a Group</button></a></p>
            </div>
            <div style="width: 48%;">
                {% if search_results %}
                    <h3>Search Results:</h3>
                    <ul>
                        {% for group, already_member in search_results %}
                            <li>
                                <a href="{% url 'social:group_detail' group_id=group.group_id %}">{{ group.name }}</a>
                                {% if already_member %}
                                    (You are already a member)
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>No groups found.</p>
                {% endif %}
                <br>
                <p><a href="{% url 'social:create_group' %}"><button>Create a Group</button></a></p>
            </div>
        </div>
    {% else %}
        <p>Login to see your groups.</p>
    {% endif %}

{% endblock %}