career/urls.py
from django.urls import path
from .views import academic_view, jobs_view

app_name="career"

urlpatterns = [
    path('academic/', academic_view, name='academic'),
    path('jobs/', jobs_view, name='jobs'),
    # other paths...
]

events/urls.py
# from django.urls import path
# from .views import events_view, delete_event

# app_name = "events"

# urlpatterns = [
#     path('events/', events_view, name='events'),
#     path('events/delete/<int:event_id>/', delete_event, name='delete_event'),
# ]



from django.urls import path
from .views import events_view, delete_event, participate_event, create_event_view

app_name = "events"

urlpatterns = [
    path('events/', events_view, name='events'),
    path('create_event/', create_event_view, name='create_event'),
    path('events/delete/<int:event_id>/', delete_event, name='delete_event'),
    path('events/participate/<int:event_id>/', participate_event, name='participate_event'),
]

home/urls.py
# home/urls.py
from django.urls import path
from .views import home, team_view, about, mission, blog

urlpatterns = [
    path('', home, name='home'),
    path('team/', team_view, name='team'),
    path('about/', about, name='about'),
    path('mission/', mission, name='mission'),
    path('blog/', blog, name='blog'),

    
]

social/urls.py
from django.urls import path
from .views import create_group, search_group, join_group, group_detail, feeds_view, create_post

app_name = 'social'

urlpatterns = [
    path('create_group/', create_group, name='create_group'),
    path('search_group/', search_group, name='search_group'),
    path('join_group/<str:group_id>/', join_group, name='join_group'),
    path('social/group_detail/<str:group_id>/', group_detail, name='group_detail'),
    path('feeds/', feeds_view, name='feeds_view'),
    path('create_post/', create_post, name='create_post'),
]

user/urls.py
# user/urls.py
from django.urls import path
from .views import signup, signin, signout, create_profile, profile, edit_profile, verify_otp
from django.urls import path
from . import views 



app_name = 'user'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('signin/', signin, name='signin'),
    path('signout/', signout, name='signout'),
    path('create_profile/', create_profile, name='create_profile'),
    path('profile/', profile, name='profile'),
    path('edit-profile/', edit_profile, name='edit_profile'), 
    path('verify_otp/', verify_otp, name='verify_otp'),


]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Connect And Collaborate</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet" />
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-4zPHaW1nOYPRFHHulckmLQtPBzSLXcYGKf7sRqpBORAMOjs=" crossorigin="anonymous"></script>


    {% block head %}{% endblock %}

</head>
    
      <body class="main-body">
    
        <nav class="navbar">
          <div class="logo">
              <a href="{% url 'home' %}">
                  <img src="{% static 'images/logo.jpg' %}" alt="Logo" class="logo-image">
              </a>
          </div>
      
          <ul class="navbar-links">
              <li class="dropdown">
                  <a href="">About Us</a>
                  <ul class="dropdown-content">
                      <li><a href="{% url 'team' %}">Team</a></li>
                      <li><a href="{% url 'mission' %}">Mission</a></li>
                      <li><a href="{% url 'blog' %}">Blog/News</a></li>
                  </ul>
              </li>
              <li class="dropdown">
                  <a href="">Features</a>
                  <ul class="dropdown-content">
                      <li><a href="{% url 'social:feeds_view' %}">Social Networking</a></li>
                      <li><a href="{% url 'events:events' %}">Events</a></li>
                      <li><a href="{% url 'career:academic' %}">Academic Resources</a></li>
                      <li><a href="{% url 'career:jobs' %}">Career Development</a></li>
                  </ul>
              </li>
              <li class="dropdown">
                  <a href="">Get Involved</a>
                  <ul class="dropdown-content">
                      <li><a href="{% url 'getinvolved:alumni_network'%}">Alumni Network</a></li>
                  </ul>
              </li>
              <li class="dropdown">
                  <a href="">Contact Us</a>
                  <ul class="dropdown-content">
                      <li><a href="{% url 'contactus:contactinfo' %}">Contact Information</a></li>
                      <li><a href="{% url 'contactus:faq' %}">FAQ</a></li>
                  </ul>
              </li>
          </ul>
      
          <div class="navbar-icons">


              <div class="nav-item-search">
                <form class="search-form" action= method="GET">
                    <input class="search-input" type="text" name="query">
                    <button type="submit" class="search-button"><i class="fa fa-search"></i></button>
                </form>
              </div>

              <div class="notification-icon">
                  <i class="material-icons" style="font-size: 1.8rem;">notifications</i>
              </div>
      
              <div class="dropdown">
                  {% if user.is_authenticated %}
                  <div class="user-profile">
                      <!-- profile.html -->
                      {% if user.userprofile.profile_picture %}
                      <img src="{{ user.userprofile.profile_picture.url }}" alt="Profile Picture" class="profile-picture">
                      {% else %}
                      <img src="/media/profile_pics/default_profile_picture.jpg" alt="Default Profile Picture"
                          class="profile-picture">
                      {% endif %}
                  </div>
                  {% else %}
                  <a class="login-text" href="{% url 'user:signin' %}">Login</a>
                  {% endif %}
      
                  {% if user.is_authenticated %}
                  <ul class="dropdown-content" style="margin-left:-50px;">
                      <li><a href="{% url 'user:profile' %}">Profile</a></li>
                      <li><a href="{% url 'user:signout' %}">Logout</a></li>
                  </ul>
                  {% else %}
                  <ul class="dropdown-content" style="margin-left:-50px;">
                      <li><a href="{% url 'user:signin' %}">Log In</a></li>
                      <li><a href="{% url 'user:signup' %}">Sign Up</a></li>
                  </ul>
                  {% endif %}
              </div>
          </div>
      </nav>
      



<div class="block-content">
    {% block content %}
        <!-- Your content goes here -->
    {% endblock %}
</div>




    <!-- Updated Footer HTML -->
    <footer class="footer">
        <div class="footer-content">
          <div class="footer-section">
            <h3 class="footer-h">Contact Us</h3>
            <p>Email: <a href="mailto:206320028@gkv.ac.in">206320028@gkv.ac.in</a></p>
            <p>Phone: <a href="tel:+919608685873">+91 9608685873</a></p>            
          </div>
          <div class="footer-section">
            <h3 class="footer-h">Quick Links</h3>
            <ul>
              <li>
                <a href="{% url 'home' %}">Home</a>
              </li>
              <li>
                <a href="{% url 'about' %}">About Us</a>
              </li>
              {% comment %} <li>
                <a href="#">Features</a>
              </li> {% endcomment %}
              {% comment %} <li>
                <a href="#">Get Involved</a>
              </li>
              <li>
                <a href="#">Privacy Policy</a>
              </li>
              <li>
                <a href="#">Terms of Service</a>
              </li> {% endcomment %}
            </ul>
          </div>
          <div class="footer-section">
            <h3 class="footer-h">Explore</h3>
            <ul>
              <li>
                <a href="{% url 'blog' %}">Blog</a>
              </li>
              <li>
                <a href="{% url 'events:events' %}">Events</a>
              </li>
              <li>
                <a href="{% url 'social:search_group' %}">Groups</a>
              </li>
            </ul>
          </div>
          <div class="footer-section">
            <h3 class="footer-h">Resources</h3>
            <ul>
              <li>
                <a href="#">FAQ</a>
              </li>
              {% comment %} <li>
                <a href="#">Support</a>
              </li> {% endcomment %}
            </ul>
          </div>
        </div>
        <div class="footer-bottom">
          <p>&copy; 2023 Connect and Collaborate | All rights reserved by Connect and Collaborate</p>
        </div>
      </footer>
    </body>
  </html>

templates/signin.html
{% load static %}
{% load socialaccount %}

<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet" />


<link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />

<script src="https://apis.google.com/js/platform.js" async defer></script>
<!-- Include Google's official CSS for the sign-in button -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">



<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Connect And Collaborate: Sign-In</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}" />
  </head>

  <body class="main-body-signin">

        <nav class="navbar">
            <div class="logo">
                <a href="{% url 'home' %}">
                    <img src="{% static 'images/logo.jpg' %}" alt="Logo" class="logo-image">
                </a>
            </div>
            
            <div class="navbar-links">

                <a href="{% url 'home' %}">
                <div class="navbar-icons-signin">
                    <div class="home-icon icon-home">
                        <i class="material-icons icon-home" style="font-size: 1.8rem;">home</i>
                    </div>
                </div>
                </a>
            </div>
        </nav>

        <div class="signin-body">

            <div class="signin-body-left">
                <div class="logo-signin">                    
                    <img src="{% static 'images/logo.jpg' %}" alt="Logo" class="logo-image-signin">
                </div>
            </div>

            <div class="signin-body-right">
                <div class="login-login">
                    <p class="login-text">Log In</p>
                    
                    <div class="login-via-google">

                        <div class="g-signin2" data-onsuccess="onSignIn"></div>

                        <!-- Custom button with Google logo -->
                        <a href="{% provider_login_url 'google' %}" onclick="onSignIn()" class="google-button">
                            <img src="https://lh3.googleusercontent.com/COxitqgJr1sJnIDe8-jiKhxDx1FrYbtRHKJ9z_hELisAlapwE9LUPh6fcXIfb5vwpbMl4xl9H9TRFPc5NOO8Sb3VSgIBrfRYvW6cUA" alt="Google Logo" width="20" height="20">
                            Continue with Google
                        </a>

                        <script>
                            function onSignIn(googleUser) {
                                // Handle sign-in logic here
                                // For example, send the user's Google ID token to your backend for verification
                                var profile = googleUser.getBasicProfile();
                                console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.
                                console.log('Name: ' + profile.getName());
                                console.log('Image URL: ' + profile.getImageUrl());
                                console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.
                            }
                            </script>

                    </div>
                    <div class="login-login-bottommost">

                        <div class="or">
                            <span class="dash"></span>
                            <p>or</p>
                            <span class="dash"></span>
                        </div>

                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-field">
                                    {{ field }}
                                    {% for error in field.errors %}
                                        <div class="error-message">{{ error }}</div>
                                    {% endfor %}
                                </div>
                            {% endfor %}
                            {% for message in messages %}
                                <div class="error-message">{{ message }}</div>
                            {% endfor %}

                            <p style="color:#000; margin-top:10px; font-size:medium;">
                                Forgot Password? <a href="{% url 'password_reset' %}" style="color:#38b6ff; margin-top:10px; font-size:medium;">Click Here</a>
                            </p>
                            
                            <button type="submit" class="login-btn">Log In</button>
                        </form>
                        
                    </div>
                </div>
<br>
                <div class="signup-login">
                    <p class="login-text">New To College Connect?</p>
                    <a href="{% url 'user:signup' %}" class="login-btn signup-btn">Sign Up</a>
                </div>

            </div>

        </div>
   
    </body> 

templates/signup.html
{% load static %}
{% load socialaccount %}

<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet" />


<link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />

<script src="https://apis.google.com/js/platform.js" async defer></script>
<!-- Include Google's official CSS for the sign-in button -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">



<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Connect And Collaborate: Sign-Up</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}" />

    <style>

    </style>

  </head>

  <body class="main-body-signup">

        <nav class="navbar">
            <div class="logo">
                <a href="{% url 'home' %}">
                    <img src="{% static 'images/logo.jpg' %}" alt="Logo" class="logo-image">
                </a>
            </div>
            
            <div class="navbar-links">

                <a href="{% url 'home' %}">
                <div class="navbar-icons-signin">
                    <div class="home-icon icon-home">
                        <i class="material-icons icon-home" style="font-size: 1.8rem;">home</i>
                    </div>
                </div>
                </a>
            </div>
        </nav>

        <div class="signup-body">

            <div class="signup-body-left">
                <div class="sign-up-main">
                    <p>Sign Up</p>

                    <div class="signup-buttons">

                        <div class="google-signup">
                            <div class="login-via-google">

                                <div class="g-signin2" data-onsuccess="onSignIn"></div>
    
                                <!-- Custom button with Google logo -->


                                <a href="{% provider_login_url 'google' %}" onclick="onSignIn()" class="google-button-signup">
                                  <img src="https://lh3.googleusercontent.com/COxitqgJr1sJnIDe8-jiKhxDx1FrYbtRHKJ9z_hELisAlapwE9LUPh6fcXIfb5vwpbMl4xl9H9TRFPc5NOO8Sb3VSgIBrfRYvW6cUA" alt="Google Logo" width="20" height="20">
                                  Continue with Google
                                </a>
    
                                <script>
                                    function onSignIn(googleUser) {
                                      // Handle sign-in logic here
                                      // For example, send the user's Google ID token to your backend for verification
                                      var profile = googleUser.getBasicProfile();
                                      console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.
                                      console.log('Name: ' + profile.getName());
                                      console.log('Image URL: ' + profile.getImageUrl());
                                      console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.
                                    }
                                </script>
    
                            </div>
                        </div>
                    </div>

                    <div class="login-login-bottommost">

                        <div style="margin-top:-2px;" class="or">
                            <span class="dash"></span>
                            <p>or</p>
                            <span class="dash"></span>
                        </div>
                        
                        <div class="form">
                            <form method="post">
                                {% csrf_token %}
                                
                                <div class="form-group">
                                    <label for="id_email_signup"></label>
                                    {{ form.email }}
                                </div>
                            
                                <div class="form-group">
                                    <label for="id_password1"></label>
                                    {{ form.password1 }}
                                </div>
                                    <small class="pass-rules">
                                        <ul style="margin:15px 30px;">
                                            <li>Passwords must be a minimum of 8 characters in length.</li>
                                            <li>Passwords must include a combination of the following:</li>
                                            <ul>
                                                <li>Uppercase letters (A-Z)</li>
                                                <li>Lowercase letters (a-z)</li>
                                                <li>Numbers (0-9)</li>
                                                <li>Special characters (!, @, #, $, %, etc.)</li>
                                                <li style="list-style:none;">                                    {% for error in field.errors %}
                                                    <div class="error-message">{{ error }}</div>
                                                    {% endfor %}
                                                    {% for message in messages %}
                                                    <div class="error-message">{{ message }}</div>
                                                    {% endfor %}
                                                    {% if form.errors %}
                                                    <ul>
                                                        {% for field, errors in form.errors.items %}
                                                            {% for error in errors %}
                                                                <li style="color:red;">{{ error }}</li>
                                                            {% endfor %}
                                                        {% endfor %}
                                                    </ul>
                                                    {% endif %}
                                                </li>
                                            </ul>
                                        </ul>                          
                                    </small>
                                <div class="form-group">
                                    <label for="id_password2"></label>
                                    {{ form.password2 }}
                                </div>
                            
                                <button type="submit" class="btn btn-primary signup-btn-signup">Continue</button>
                            </form>
                        </div>
                    </div>

                    <br>
                    <br>
                    <br>

                </div>


                
            </div>

            <div class="signup-body-right">

                <div class="signup-login-signup">
                    <p class="login-text-signup">Already have an account?</p>
                    <a href="{% url 'user:signin' %}" class="login-btn-signup">Log In</a>
                </div>

            </div>

        </div>
   
    </body> 